services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    command: --replSet rs0
    environment:
      MONGO_INITDB_DATABASE: olympus-banking
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
      - ./mongo/init/:/docker-entrypoint-initdb.d/:ro

volumes:
  mongodb:
    driver: local
